server:
  port: 9999

spring:
  application:
    name: dips-gateway
  # 配置中心
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: dips-config
  profiles:
    active: dev

# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://dips:dips@127.0.0.1:1025/eureka/
